# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PageTemplate - 副本.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QHBoxLayout, QLayout,
    QListWidgetItem, QSizePolicy, QSpacerItem, QVBoxLayout,
    QWidget)

from qfluentwidgets import (CardWidget, ElevatedCardWidget, HorizontalFlipView, HorizontalPipsPager,
    IndeterminateProgressBar, OpacityAniStackedWidget, PrimaryPushButton, PushButton,
    SimpleCardWidget, SmoothScrollArea, SpinBox, SubtitleLabel)
import V4Resources_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(989, 668)
        Form.setStyleSheet(u"border-image: url(:/PNG/PNG/oyama-mahiro-ai~1.png);")
        self.verticalLayout = QVBoxLayout(Form)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.OpacityAniStackedWidget = OpacityAniStackedWidget(Form)
        self.OpacityAniStackedWidget.setObjectName(u"OpacityAniStackedWidget")
        self.OpacityAniStackedWidget.setStyleSheet(u"border-image: transparent;\n"
"background: transparent;")
        self.API_Page = QWidget()
        self.API_Page.setObjectName(u"API_Page")
        self.horizontalLayout_2 = QHBoxLayout(self.API_Page)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.SimpleCardWidget = SimpleCardWidget(self.API_Page)
        self.SimpleCardWidget.setObjectName(u"SimpleCardWidget")
        self.SimpleCardWidget.setMinimumSize(QSize(361, 0))
        self.SimpleCardWidget.setMaximumSize(QSize(361, 16777215))
        self.verticalLayout_3 = QVBoxLayout(self.SimpleCardWidget)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.SmoothScrollArea = SmoothScrollArea(self.SimpleCardWidget)
        self.SmoothScrollArea.setObjectName(u"SmoothScrollArea")
        self.SmoothScrollArea.setStyleSheet(u"background: transparent;\n"
"border: none;")
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setAlignment(Qt.AlignCenter)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 343, 614))
        self.gridLayout_2 = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.StartButton = PrimaryPushButton(self.scrollAreaWidgetContents)
        self.StartButton.setObjectName(u"StartButton")

        self.gridLayout_2.addWidget(self.StartButton, 6, 0, 1, 3)

        self.verticalSpacer_21 = QSpacerItem(10, 10, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.gridLayout_2.addItem(self.verticalSpacer_21, 7, 0, 1, 1)

        self.verticalSpacer_7 = QSpacerItem(20, 0, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.gridLayout_2.addItem(self.verticalSpacer_7, 4, 0, 1, 1)

        self.ProgressLine = IndeterminateProgressBar(self.scrollAreaWidgetContents)
        self.ProgressLine.setObjectName(u"ProgressLine")

        self.gridLayout_2.addWidget(self.ProgressLine, 8, 0, 1, 3)

        self.verticalSpacer_9 = QSpacerItem(20, 20, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_2.addItem(self.verticalSpacer_9, 9, 0, 1, 1)

        self.verticalSpacer_4 = QSpacerItem(20, 20, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.gridLayout_2.addItem(self.verticalSpacer_4, 1, 1, 1, 1)

        self.verticalSpacer_8 = QSpacerItem(20, 30, QSizePolicy.Minimum, QSizePolicy.Preferred)

        self.gridLayout_2.addItem(self.verticalSpacer_8, 5, 1, 1, 1)

        self.SubtitleLabel_2 = SubtitleLabel(self.scrollAreaWidgetContents)
        self.SubtitleLabel_2.setObjectName(u"SubtitleLabel_2")

        self.gridLayout_2.addWidget(self.SubtitleLabel_2, 3, 0, 1, 3)

        self.SubtitleLabel = SubtitleLabel(self.scrollAreaWidgetContents)
        self.SubtitleLabel.setObjectName(u"SubtitleLabel")
        font = QFont()
        font.setFamilies([u"HarmonyOS Sans SC"])
        font.setPointSize(20)
        font.setBold(False)
        self.SubtitleLabel.setFont(font)
        self.SubtitleLabel.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.SubtitleLabel, 0, 0, 1, 3)

        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_3.addWidget(self.SmoothScrollArea)


        self.horizontalLayout_2.addWidget(self.SimpleCardWidget)

        self.widget = QWidget(self.API_Page)
        self.widget.setObjectName(u"widget")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QSize(361, 0))
        self.widget.setLayoutDirection(Qt.LeftToRight)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet(u"QVBoxLayout {\n"
"    alignment: center;\n"
"}")
        self.verticalLayout_4 = QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(-1, 1, -1, -1)
        self.ElevatedCardWidget = ElevatedCardWidget(self.widget)
        self.ElevatedCardWidget.setObjectName(u"ElevatedCardWidget")
        self.ElevatedCardWidget.setMinimumSize(QSize(0, 450))
        self.ElevatedCardWidget.setMaximumSize(QSize(16777215, 16777215))
        self.verticalLayout_10 = QVBoxLayout(self.ElevatedCardWidget)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.Images_Area = HorizontalFlipView(self.ElevatedCardWidget)
        self.Images_Area.setObjectName(u"Images_Area")

        self.verticalLayout_10.addWidget(self.Images_Area)


        self.verticalLayout_4.addWidget(self.ElevatedCardWidget)

        self.widget_7 = QWidget(self.widget)
        self.widget_7.setObjectName(u"widget_7")
        self.widget_7.setMaximumSize(QSize(16777215, 51))
        self.horizontalLayout = QHBoxLayout(self.widget_7)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalSpacer_5 = QSpacerItem(210, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_5)

        self.horizontalSpacer_9 = QSpacerItem(40, 20, QSizePolicy.Preferred, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_9)

        self.Images_Indicator = HorizontalPipsPager(self.widget_7)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        QListWidgetItem(self.Images_Indicator)
        self.Images_Indicator.setObjectName(u"Images_Indicator")

        self.horizontalLayout.addWidget(self.Images_Indicator)

        self.horizontalSpacer_7 = QSpacerItem(210, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_7)

        self.Images_Switcher = SpinBox(self.widget_7)
        self.Images_Switcher.setObjectName(u"Images_Switcher")
        self.Images_Switcher.setMaximumSize(QSize(150, 33))
        self.Images_Switcher.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Images_Switcher.setMinimum(1)
        self.Images_Switcher.setMaximum(100)

        self.horizontalLayout.addWidget(self.Images_Switcher)


        self.verticalLayout_4.addWidget(self.widget_7)


        self.horizontalLayout_2.addWidget(self.widget)

        self.OpacityAniStackedWidget.addWidget(self.API_Page)

        self.verticalLayout.addWidget(self.OpacityAniStackedWidget)


        self.retranslateUi(Form)

        self.OpacityAniStackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.StartButton.setText(QCoreApplication.translate("Form", u"\u751f\u6210", None))
        self.SubtitleLabel_2.setText(QCoreApplication.translate("Form", u"<html><head/><body><p><span style=\" font-size:15pt;\">Content</span></p></body></html>", None))
        self.SubtitleLabel.setText(QCoreApplication.translate("Form", u"API Title", None))

        __sortingEnabled = self.Images_Indicator.isSortingEnabled()
        self.Images_Indicator.setSortingEnabled(False)
        ___qlistwidgetitem = self.Images_Indicator.item(255)
        ___qlistwidgetitem.setText(QCoreApplication.translate("Form", u"6", None));
        self.Images_Indicator.setSortingEnabled(__sortingEnabled)

    # retranslateUi

